### ISSUE TITLE
Signal bot down

### ISSUE THREAD

**Issue by pstn** [eknoes/covid-bot#101]
Ich habe heute mein Abo nicht erhalten und den Bot deshalb vor 10 Minuten mit `abo` angeschrieben und dafür nicht einmal eine Empfangsbestätigung bekommen. Mit meinen menschlichen Kontakten kann ich hingegen normal schreiben.

**Comment by eknoes** [comment]
Ja, wir haben heute morgen zu viele Berichte auf einmal verschickt und wurden vom Rate Limiting getroffen. Das ist jetzt "korrekter" implementiert, wir wissen aber nicht wann wir wieder senden können. Siehe #100. Wir haben das versucht auf der Website zu vermerken. Ich hoffe, dass wir morgen früh wieder entsperrt sind, bzw. dass es eine zeitlich begrenzte Sperrung ist.

**Comment by pstn** [comment]
Ah, ich wusste nicht, dass das auch Empfangen betrifft und wollte das nur kurz melden. Ich mach mal wieder zu.
