### ISSUE TITLE
Sortierung der Orte im täglichen Bericht

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#19]
Derzeit scheinen die Orte nach dem Zeitpunkt des Abonnements sortiert zu werden (Neueste zuerst). Sinnvoller ist eine alphabetische Sortierung, würde ich sagen. Was meinst du?

**Comment by eknoes** [comment]
Ich finde eine Kategorisierung nach Inzidenzstufen, bspw. 35, 50, 100, 200 sinnvoll und innerhahalb dieser alphabetisch sinnvoll.

**Comment by eknoes** [comment]
Gemeinsam mit #21

**Comment by errotu** [comment]
Bei mir fehlt innerhalb der Inzidenzstufen noch die alphabetische Sortierung.

**Comment by eknoes** [comment]
Danke für den hint, ist jetzt drin!

**Comment by errotu** [comment]
Bundesländer sind seit der Trennung nicht mehr sortiert, sollte durch #34 gefixt sein, vielleicht kannst du da aber vor dem Mergen nochmal draufschauen.

Würde außerdem vorschlagen, dass wir das Issue offenlassen, solange er bei den Orten noch nicht nach dem eigentlichen Ortsnamen, sondern SK/LK sortiert.

**Comment by eknoes** [comment]
Durch https://github.com/eknoes/covid-bot/commit/86071721ee5fa8019595201cd7495e236a49fb7e heißen die ab dem nächsten RKI Update bspw. Kassel (Landkreis) und dadurch ist es auch sortiert. Ich weiß aber schon nicht mehr ob mir das so gefällt, bspw. bei Region Hannover -> Hannover (Region). Was denkst du dazu?

**Comment by errotu** [comment]
Finde ich so spontan erstmal gut! Die Änderungen sind aber noch nicht live, oder?

**Comment by eknoes** [comment]
Doch, das wurde aber erst mit dem neuen Datensatz in die Datenbank eingepflegt.

**Comment by eknoes** [comment]
Läuft jetzt.
