### ISSUE TITLE
 Ortsauswahl benutzerfreundlicher gestalten III - PLZ und Orte, die keine Stadt-/Landkreise sind

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#22]
Über [Nominatim](https://nominatim.org/release-docs/develop/api/Search/) (siehe #18) sollten auch sowohl eine Ortsangabe über die PLZ als auch ein Mapping von Orten, die selbst keine Stadt- oder Landkreise sind, zu dem dazugehörigen Stadt-/Landkreis recht problemlos funktionieren.

Leider zeigt die Suche nicht unmittelbar den Wert für "county" an, den müsste man dann noch über die Reverse Search mit der ausgegebenen Länge und Breite ermitteln.

Beispiel für PLZ-Suche (69181 ist Leimen im Rhein-Neckar-Kreis):
https://nominatim.openstreetmap.org/search?format=json&countrycodes=de&postalcode=69181

Beispiel für die Suche nach einem Ort, der in einem Landkreis liegt:
https://nominatim.openstreetmap.org/search?format=json&countrycodes=de&city=leimen

**Comment by eknoes** [comment]
Wie genau müssen wir denen Credit geben? Auch im Bot? https://www.openstreetmap.org/copyright

**Comment by errotu** [comment]
Ich gehe davon aus, dass unsere aktuelle Nennung in den Credits ausreicht. Vgl. hierzu:

> For a printed map, the credit should appear beside the map if that is where other such credits appear, and/or in the "acknowledgements" section of the publication (often at the start of a book or magazine). [...]
> As an electronic database or collection of databases, file, CD, Place the text in the file itself or in an extra file.

https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ

**Comment by errotu** [comment]
Der Commit funktioniert übrigens super bei mir! Würde nur vorschlagen, dass wir die Vorgehensweise noch erklären. Also jeweils bspw. jeweils die folgenden Aussage vor die Abfrage ob Bericht oder Abo stellen:
"Für [Ort] stellt das RKI leider keine spezifischen Daten zur Verfügung. Du kannst stattdessen die Zahlen des dazugehörigen Landkreises abrufen."

**Comment by eknoes** [comment]
Wenn mehrere Orte gefunden werden senden wir diese Nachricht seit acf95c0c22383156e76e75dc0c0044212480e2b3 wenn man nur einen Treffer hat gerade nicht, das ist aufwändiger
