### ISSUE TITLE
Reset-Funktion integrieren

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#29]
Es sollte einen Befehl geben, um das bestehende Nutzerprofil zu löschen (also alle Orte zu entfernen). Danach sollte der Befehl /start ausgelöst werden.

**Comment by eknoes** [comment]
Wir können zwar alle Daten löschen, aber nicht den Chat leeren / beenden. Das ist über die API nicht möglich, weshalb ich dann auch /start nicht erneut auslösen würde.
