### ISSUE TITLE
Lizenzen der Libraries 

### ISSUE THREAD

**Issue by eknoes** [eknoes/covid-bot#30]
Inwieweit müssen wir die Bibliotheken, die wir benutzen, referenzieren? Die stehen alle in der Datei requirements.txt! Ist das abhängig von deren Lizenz?

**Comment by errotu** [comment]
Ja, ist abhängig von der Lizenz. Ich habe jetzt alle mal mit #31 in die "Credits" aufgenommen (wobei das wohl nicht immer notwendig ist, aber doch ein schönes Zeichen, wie ich finde). Bitte dann bei neuen Bibliotheken auch unmittelbar dort nach folgendem Schema aufnehmen (ist angelehnt an die Voraussetzungen der MIT Lizenz):

> * [NAME](URLHOMEPAGE), LICENSE, Copyright (c) 2021 AUTHOR

Alle Informationen gibt es unmittelbar bei [PyPI](https://pypi.org/).

**Comment by eknoes** [comment]
Cool wäre ja ein Skript, dass das aus den Abhängigkeiten generiert!
