### ISSUE TITLE
Bundesweite 7-Tage-Inzidenz angeben

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#32]
Es wäre gut, wenn wir im Einleitungstext neben den Infektionen und Todesfällen auch die bundesweite Inzidenz angeben würden.

**Comment by eknoes** [comment]
Die müssen wir selbst ausrechnen, aber da wir Einwohnerzahlen und so haben wäre das möglich!

**Comment by eknoes** [comment]
Unser errechneter Wert weicht leider von den RKI Zahlen ab, ich denke deswegen:

> Die 7-Tage-Inzidenz basiert auf dem Meldedatum der Fälle, das ist der Zeitpunkt, an dem der Fall dem Gesundheitsamt bekannt wird. Durch den Übermittlungsverzug kann es zu einer Unterschätzung der 7-Tage-Inzidenz kommen, insbesondere bei dynamischen Entwicklungen, da noch nicht alle Daten vollständig vorliegen.
https://www.rki.de/SharedDocs/FAQ/NCOV2019/gesamt.html

Wir haben allerdings die Daten nur nach der RKI Veröffentlichung, das - soweit ich das verstehe - von dem Meldedatum abweichen kann. Dafür gibt es das deutlich komplexere Datenset: https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0?orderBy=Refdatum&selectedAttribute=Meldedatum

Soweit ich das sehe, könnten wir also eine 7 Tage Inzidenz angeben, welche aber leicht von den RKI Daten abweichen würde. Was denkst du dazu?

Bspw. für 22.01.: RKI meldet 115.3, wir würden 126.61 melden.

**Comment by errotu** [comment]
Ich glaube, wir können es doch berechnen, indem wir die offizielle Inzidenz der Landkreise (oder der Bundesländer, das ist eigentlich egal) nehmen, jeweils mit der Einwohnerzahl als Faktor multiplizieren und dann wieder durch die Summe der Einwohner:innen aller Landkreise (also der Einwohner:innen Deutschlands) teilen.
Habe das gerade mal für den 23. Januar in Calc getestet und komme auf den Wert 111,13, das entspricht [dem Wert im COVID 19-Dashboard (111,1)](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4).

[RKI_BundesweiteInzidenz_2021-01-24.xlsx](https://github.com/eknoes/covid-bot/files/5863078/RKI_BundesweiteInzidenz_2021-01-24.xlsx)

**Comment by eknoes** [comment]
Top, da habe ich nicht dran gedacht. Das funktioniert!
