### ISSUE TITLE
Zahlen falsch

### ISSUE THREAD

**Issue by eknoes** [eknoes/covid-bot#35]
Alle außer uns melden nur 9847 Neuinfektionen, wir über 19.000

**Comment by errotu** [comment]
Wir scheinen doppelt zu zählen. Sowohl die Neuinfektionen als auch die Todeszahlen sind bei uns exakt doppelt so hoch wie in den offiziellen Zahlen. Könntest du (auch schon vor dem Bugfix) eine kurze Korrektur via Telegram verschicken?

**Comment by eknoes** [comment]
Oh dann weiß ich auch wo ich den Bug introduced habe 🙈 Wird gefixt und dann schicke ich ne Korrektur - den Mechanismus dafür muss ich aber auch erst noch bauen.
