### ISSUE TITLE
Grafiken mit History

### ISSUE THREAD

**Issue by eknoes** [eknoes/covid-bot#43]
Wir könnten zu den Berichten Grafiken generieren, damit man die Anzahl der Neuinfektionen besser einordnen kann. Bspw mit matplotlib

**Comment by errotu** [comment]
Finde ich gut! Gehe aber davon aus, dass #33 deutlich einfacher umzusetzen wäre und sich deshalb vielleicht als erster Schritt in diese Richtung anbietet?

**Comment by eknoes** [comment]
Ja, auf jeden Fall!
