### ISSUE TITLE
Impfquotenmonitoring einarbeiten

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#44]
Das RKI stellt die Zahlen [für das Impfquotenmonitoring](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) derzeit leider nur als Excel-Datei und ohne explizite Nennung einer Lizenz zur Verfügung.
Eine Anfrage bzgl. der Verwendung und das Bereitstellen über eine standardisierte Schnittstelle wurde am 10. Januar 2021 an das RKI gesendet.

Falls es keine Lizenzprobleme gibt, wie aufwendig wäre es, die Zahlen der Excel-Datei automatisiert zu verarbeiten, @eknoes? Die URL der Datei scheint derzeit stabil zu sein.

**Comment by eknoes** [comment]
Müsste mit https://foss.heptapod.net/openpyxl/openpyxlrelativ gut umzusetzen sein, solange das RKI die Tabelle nicht ändert was die Spaltenbezeichnungen o.Ä. angeht!

**Comment by eknoes** [comment]
Hier gibt es die Daten maschinenlesbar aber unter unklarer Lizenz: https://services.arcgis.com/OLiydejKCZTGhvWg/ArcGIS/rest/services/BL_mit_Impfdaten_join/FeatureServer/0

**Comment by errotu** [comment]
Die Excel-Tabelle dürften wir nach der (für mich plausiblen) Einschätzung aus #50 wohl weiterverwenden (Hervorhebungen von mir):

> Problem: Das RKI stellt die Infektionszahlen in einer Excelliste bereit und versieht diese nicht mit einer Lizenz.
> Das RKI ist eine selbstständige Bundesoberbehörde i.S.d. Art. 87 Abs. 3 S. 1 GG. Damit gehört es zur mittelbaren Bundesverwaltung, die derzeit nicht in den Anwendungsbereich von § 12a EGovG fällt. Das RKI unterliegt damit keiner originären „Open-Data-Pflicht.
> Das RKI veröffentlicht aber freiwillig und proaktiv eine Excelliste. Diese Daten unterfallen dem IWG. Schließlich ist das RKI als selbstständige Bundesbehörde eine „öffentliche Stelle“ i.S.d. § 2 Abs. 1 Nr. 1 lit. b IWG. Da das RKI die Daten veröffentlicht, also jedermann freiwillig zur Verfügung stellt, kommt es nicht mehr darauf an, ob ein Zugangsrecht für die Daten bestünde (BVerwG, Urt. v. 14.4.2016 – 7 C 12/14 (VGH Mannheim).
> **Dementsprechend gilt § 2a S. 1 IWG „Informationen, die in den Anwendungsbereich dieses Gesetzes fallen, dürfen weiterverwendet werden“**. Zwar dürfen öffentliche Stellen bereitgestellte Daten mit sog. Nutzungsbedingungen versehen (§ 4 IWG). Dies gebietet auch die „gute Praxis“. Solche Nutzungsbedingungen schaffen Rechtsklarheit. Soweit die öffentliche Stelle aber keine (einschränkenden) Nutzungsbedingungen erlässt, vermittelt § 2a IWG ipso iure einen ErlaubnisTB, die bereitgestellten Daten zu nutzen. Dass das RKI mutmaßlich ein Datenbankherstellerrecht an diesen Daten inne hat, ist m.E. unschädlich. Zwar sieht das IWG vor, dass Datensätze, die von Urheberrechten, verwandten Schutzrechten oder gewerblichen Schutzrechten Dritter erfasst werden, nicht dem IWG unterfallen (§ 1 Abs. 2 Nr. 4 IWG). Das RKI ist aber öffentliche Stelle i. S. d. § 2 Abs. 1 Nr. 1 lit. b IWG und damit gerade kein Dritter i. S. d. § 1 Abs. 2 Nr. 4 IWG.
> **Danach dürfen die vom RKI bereitgestellten Daten nach meiner kursorischen Einschätzung weiterverwendet werden.**
> Zu klären bleibt noch, ob ggf. ein Anspruch auf Bereitstellung der Daten in einem anderen Format besteht. Ein solcher kann sich ggf. originär aus dem IFG ergeben. Zudem könnte sich ein solcher Anspruch auch aus der Art. 5 Abs. 1 PSI-RL 2013 ergeben. Diese setzt das IWG m.E. nicht richtlinienkonform um. Dazu gibt es aber keine Rechtsprechung. Selbst wenn man Art. 5 Abs. 1 PSI-RL 2013 für unmittelbar anwendbar erklärt, könnte sich das RKI aber womöglich auf Art. 5 Abs. 2 PSI-RL 2013 berufen. Ein möglicher Anspruch aus dem IFG hätte die selbe Hürde des „verhältnismäßigen Aufwandes“ zu nehmen, vgl. § 1 Abs. 2 S. 2 IFG Bund.
> Womöglich könnte das RKI sich auch auf § 1 Abs. 2 Nr. 6 IWG berufen, um zu begründen, warum es dem IWG nicht unterfällt. Richter, IWG, Kommentar § 1 Rn. 519 führt hierzu aus: „Es muss sich um wissenschaftliche Forschung handelt. Diese umfasst nach Ansicht des BVerfG eine ‚geistige Tätigkeit mit dem Ziel, in methodischer, systematischer und nachprüfbarer Weise neue Erkenntnisse zu gewinnen [BVerfGE 35, 113]. Die Einrichtung muss sich in ihrem niedergelten Zweck nach der Forschung verschrieben haben. Nicht ausreichend ist, wenn ein tatsächlicher Schwerpunkt auf der Forschung liegt.“ Richter § 1 Rn. 520 „Im Zweifelsfall ist die Ausnahme […] in Bezug auf die Forschung eng auszulegen.“ Vgl. auch KOM SEC (2011) 1152 final, 33 f.
> [Subsumtion des RKI unter diese VSS überlasse ich euch. Ich gehe aber nicht davon aus, dass sich das RKI darauf berufen kann, da es neben seinem Zweck nach weniger der Forschung, als vielmehr der Gefahrenabwehr zu dienen scheint, vgl. Wikipedia.].
> Aus demselben Grund ist das RKI wohl auch eine „Einrichtung für den Transfer von Forschungsergebnissen“ i. S. d. § 1 Abs. 2 Nr. 6 IWG.

**Comment by errotu** [comment]
Die maschinenlesbare Version wird wohl von Esri zur Verfügung gestellt. Ein Rechtsanspruch auf Weiterverwendung der Daten wie beim RKI gibt es wohl eher nicht (weil Esri keine öffentliche Institution ist), auf der anderen Seite dürfte die reine Konvertierung der Daten in ein anderes Format meines Erachtens noch keinen urheberrechtlichen Schutz auslösen. Ich würde deshalb vorschlagen, dass wir die maschinenlesbaren Daten von Esri verwenden (vorher aber stichprobenartig überprüfen, ob sie mit der Excel-Datei übereinstimmen).

**Comment by eknoes** [comment]
Hier bei Terms of Use zu den Impfdaten: https://www.arcgis.com/home/item.html?id=7c4736966e614ade90b84e41f129ff90

No special restrictions or limitations on using the item's content have been provided.

**Comment by eknoes** [comment]
Die Datenquellen werden nicht mehr aktualisiert. Dafür habe ich das Impfdashboard gefunden: https://impfdashboard.de/
Wahrscheinlich werden unsere Quellen nicht aktualisiert, da:

> Version 1 der Daten beinhaltet keine Information zur Erst- und Zweitimpfung, wird seit 18. Januar nicht weiter aktualisiert und ist hier archiviert.

Darüber gibt es allerdings nur bundesweite Daten. 

Ansonsten gibt es jetzt:

- https://services.arcgis.com/OLiydejKCZTGhvWg/ArcGIS/rest/services/Impftabelle_mit_Zweitimpfungen/FeatureServer/0 (letzte Aktualisierung 30.1.)

Mit Aufschlüsselung nach Bundesländer. Da müssen wir mal ein Auge drauf haben, wie das aktualisiert wird. Das Impfdashboard und die RKI Tabelle sind da aktueller.

**Comment by eknoes** [comment]
Die Daten der ZEIT sind auch vom 30.1. - vielleicht haben sie die selbe Quelle? https://www.zeit.de/wissen/gesundheit/2021-01/corona-impfung-deutschland-anzahl-impfquote-aktuelle-zahlen-karte

**Comment by errotu** [comment]
Hast du die tsv-Datei auf dem Impfdashboard gesehen? Ich denke, die dürften wir auswerten. Meinst du, das klappt technisch?

**Comment by eknoes** [comment]
Ja, aber dann haben wir nur bundesweite Daten - bei ArcGis hätten wir sie auch für die Länder. Dafür wären die Daten immer eher einen Tag zu spät. Was denkst du?

**Comment by eknoes** [comment]
Wobei: Das RKI veröffentlicht die Daten morgens, die TSV ändert sich um 10 Uhr - das heißt da wären wir morgens im Report, solange das RKI nicht mal wieder lange braucht - auch nicht aktuell.
