### ISSUE TITLE
R-Wert anzeigen

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#45]
Können wir den jeweiligen R-Wert für die Städte auch angeben?

**Comment by eknoes** [comment]
Ich weiß nicht, wie der berechnet wird. Kann sein, dass wir das selbst ausrechnen können, angegeben in unseren Daten ist er nicht!

**Comment by errotu** [comment]
Das RKI stellt die relevanten Daten [hier zur Verfügung](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html). Der Link zur CSV-Datei scheint halbwegs stabil zu sein. [Hier](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/R-Beispielrechnung.xlsx?__blob=publicationFile) gibt es Angaben zur Berechnung des R-Werts.
[Dieses Projekt](https://github.com/marlon360/rki-covid-api) stellt ebenfalls Corona-Daten zur Verfügung. Wir könnten uns überlegen, ob wir deren Daten-Endpunkt nutzen oder uns zumindest bei der Berechnung (natürlich in beiden Fällen mit entsprechenden Credits) [an ihnen orientieren](https://github.com/marlon360/rki-covid-api/blob/v2/src/data-requests/r-value.ts).

**Comment by eknoes** [comment]
Added in 09380980
