### ISSUE TITLE
/start von /hilfe entkoppeln

### ISSUE THREAD

**Issue by eknoes** [eknoes/covid-bot#49]
Aktuell bekommt man beim /start den langen Hilfetext angezeigt - das schreckt imho ab. Wir könnten einen interaktiven Start ermöglichen, also nach dem Motto: 
* Hi wir machen X, schick uns mal nen Ort oder Standort um den Ort zu abonnieren oder aktuelle Daten abzufragen
* Nutzer sendet Ort
* Befehl bearbeiten + "Super danke, alle Funktionen findest du über /hilfe"

**Comment by errotu** [comment]
Finde ich super, perspektivisch sollte die erste Abfrage wohl die Sprache sein (#10).
