### ISSUE TITLE
Nutzungsbefugnis und Formate RKI Daten und DIVI Daten

### ISSUE THREAD

**Issue by dvidwgner** [eknoes/covid-bot#50]
Unverbindliche Einschätzung, die ausdrücklich keine Rechtsberatung darstellt!
Problem: Das RKI stellt die Infektionszahlen in einer Excelliste bereit und versieht diese nicht mit einer Lizenz.
Das RKI ist eine selbstständige Bundesoberbehörde i.S.d. Art. 87 Abs. 3 S. 1 GG. Damit gehört es zur mittelbaren Bundesverwaltung, die derzeit nicht in den Anwendungsbereich von § 12a EGovG fällt. Das RKI unterliegt damit keiner originären „Open-Data-Pflicht.
Das RKI veröffentlicht aber freiwillig und proaktiv eine Excelliste. Diese Daten unterfallen dem IWG. Schließlich ist das RKI als selbstständige Bundesbehörde eine „öffentliche Stelle“ i.S.d. § 2 Abs. 1 Nr. 1 lit. b IWG. Da das RKI die Daten veröffentlicht, also jedermann freiwillig zur Verfügung stellt, kommt es nicht mehr darauf an, ob ein Zugangsrecht für die Daten bestünde (BVerwG, Urt. v. 14.4.2016 – 7 C 12/14 (VGH Mannheim).
Dementsprechend gilt § 2a S. 1 IWG „Informationen, die in den Anwendungsbereich dieses Gesetzes fallen, dürfen weiterverwendet werden“. Zwar dürfen öffentliche Stellen bereitgestellte Daten mit sog. Nutzungsbedingungen versehen (§ 4 IWG). Dies gebietet auch die „gute Praxis“. Solche Nutzungsbedingungen schaffen Rechtsklarheit. Soweit die öffentliche Stelle aber keine (einschränkenden) Nutzungsbedingungen erlässt, vermittelt § 2a IWG ipso iure einen ErlaubnisTB, die bereitgestellten Daten zu nutzen. Dass das RKI mutmaßlich ein Datenbankherstellerrecht an diesen Daten inne hat, ist m.E. unschädlich. Zwar sieht das IWG vor, dass Datensätze, die von Urheberrechten, verwandten Schutzrechten oder gewerblichen Schutzrechten Dritter erfasst werden, nicht dem IWG unterfallen (§ 1 Abs. 2 Nr. 4 IWG). Das RKI ist aber öffentliche Stelle i. S. d. § 2 Abs. 1 Nr. 1 lit. b IWG und damit gerade kein Dritter i. S. d. § 1 Abs. 2 Nr. 4 IWG. 
Danach dürfen die vom RKI bereitgestellten Daten nach meiner kursorischen Einschätzung weiterverwendet werden.
Zu klären bleibt noch, ob ggf. ein Anspruch auf Bereitstellung der Daten in einem anderen Format besteht. Ein solcher kann sich ggf. originär aus dem IFG ergeben. Zudem könnte sich ein solcher Anspruch auch aus der Art. 5 Abs. 1 PSI-RL 2013 ergeben. Diese setzt das IWG m.E. nicht richtlinienkonform um. Dazu gibt es aber keine Rechtsprechung. Selbst wenn man Art. 5 Abs. 1 PSI-RL 2013 für unmittelbar anwendbar erklärt, könnte sich das RKI aber womöglich auf Art. 5 Abs. 2 PSI-RL 2013 berufen. Ein möglicher Anspruch aus dem IFG hätte die selbe Hürde des „verhältnismäßigen Aufwandes“ zu nehmen, vgl. § 1 Abs. 2 S. 2 IFG Bund.
Womöglich könnte das RKI sich auch auf § 1 Abs. 2 Nr. 6 IWG berufen, um zu begründen, warum es dem IWG nicht unterfällt. Richter, IWG, Kommentar § 1 Rn. 519  führt hierzu aus: „Es muss sich um wissenschaftliche Forschung handelt. Diese umfasst nach Ansicht des BVerfG eine ‚geistige Tätigkeit mit dem Ziel, in methodischer, systematischer und nachprüfbarer Weise neue Erkenntnisse zu gewinnen [BVerfGE 35, 113]. Die Einrichtung muss sich in ihrem niedergelten Zweck nach der Forschung verschrieben haben. Nicht ausreichend ist, wenn ein tatsächlicher Schwerpunkt auf der Forschung liegt.“ Richter § 1 Rn. 520 „Im Zweifelsfall ist die Ausnahme […] in Bezug auf die Forschung eng auszulegen.“ Vgl. auch KOM SEC (2011) 1152 final, 33 f.
[Subsumtion des RKI unter diese VSS überlasse ich euch. Ich gehe aber nicht davon aus, dass sich das RKI darauf berufen kann, da es neben seinem Zweck nach weniger der Forschung, als vielmehr der Gefahrenabwehr zu dienen scheint, vgl. Wikipedia.]. 
Aus demselben Grund ist das RKI wohl auch eine „Einrichtung für den Transfer von Forschungsergebnissen“ i. S. d. § 1 Abs. 2 Nr. 6 IWG.
Die DIVI stellt ihre Zahlen für die Intensivbettenbelegung nicht allgemein frei lizenziert bereit, sondern man immer explizit anfragen muss (und wir darauf seit drei Wochen keine Antwort erhalten).
Die DIVI ist ein e.V. Die Mitglieder bestehen aus Ärzten, also Privatleuten. Einige dieser Ärzte arbeiten bei Krankenhäusern in öffentlich-rechtlicher Trägerschaft. Das trifft aber sicher nicht auf alle Mitglieder zu. Eine Konstruktion eines Anspruchs aus einem IFG oder dem IWG gegenüber DIVI ist dann wohl nicht möglich.
Gegenüber den öffentlich-rechtlichen Trägern könnte man Informationszugangsansprüche nach dem jeweiligen Landes-IFG gelten machen. Ein Anspruch auf Weiterverwendung der Daten ergibt sich dann aus § 2a IWG. Gegenüber Krankenhäusern in privater Trägerschaft könnten auch Ansprüche aus dem jeweils geltenden Landes-IFG bestehen. Private Einrichtungen unterfallen dem IFG regelmäßig aber nur soweit eine Behörde sich dieser Person zur Erfüllung ihrer öffentlich-rechtlichen Aufgaben bedient (Vgl. § 1 Abs. 1 S. 3 IFG Bund; viele Landes-IFG sind an diese Regelung zumindest angelehnt). Ob dies der Fall ist, kann ich mangels Kenntnis des „Krankenhausrechts“ aber nicht beurteilen. 
Sofern ein Krankenhaus dem Anwendungsbereich eines Landes-IFG unterfällt, besteht grds. ein Anspruch auf Zugang zu der Information. Dieser darf nur gestützt auf einen Ausnahmegrund verweigert werden. Ohne nähere Prüfung gehe ich aber nicht davon aus, dass es sich bei den Informationen um besonders schutzwürdige Informationen handelt, die etwaigen Ausnahmegründen nach den Landes-IFG unterfallen. Ich gebe aber zu bedenken, dass ein solcher Anspruch notfalls eingeklagt werden müsste. 
Informationen müssen grds. in dem angefragten Format bereitgestellt werden, es sei denn, für die Behörde ist damit ein „unverhältnismäßiger Aufwand“ verbunden. Hier würde ich davon ausgehen, dass ein Gericht sich schwer damit tuen sollte, einen solchen Aufwand zu erkennen. Schließlich ist davon auszugehen, dass die Informationen von DIVI gleichsam nicht händisch zusammengetragen werden, sondern in entsprechenden Formaten bereitgestellt werden. Das ist natürlich aber nur eine Annahme.

**Comment by errotu** [comment]
Super, vielen Dank für die rechtliche Einschätzung! Ich schließe es hier mal und füge es jeweils in die betreffenden Issues ein.
