### ISSUE TITLE
Trends werden für den Bund nicht korrekt ermittelt

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#56]
Die Trends sollten eigentlich immer mit Ihrem Pendant vor einer Woche verglichen werden, richtig?
Das scheint bei den Bundesangaben nicht ganz zu funktionieren:

> **Corona-Bericht vom 20.01.2021**
> 
> Insgesamt wurden bundesweit 15.974 Neuinfektionen ↗️ und 1.148 Todesfälle ↗️ gemeldet.

> **Corona-Bericht vom 27.01.2021**
> 
> Insgesamt wurden bundesweit 13.202 Neuinfektionen ↗️ **[falsch, gesunken]** und 982 Todesfälle ↗️ **[falsch, gesunken]** gemeldet. Die 7-Tage-Inzidenz liegt bei 100,95 ↘️ _**[kann ich gerade nicht verifizieren]**_.

**Comment by eknoes** [comment]
Wollten wir noch so implementieren, aktuell vergleichen unsere Trends aber immer mit dem Vortag!
