### ISSUE TITLE
Formatierung

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#57]
Bei Signal gibt es ein paar kleinere Formatierungsfehler:

- Umlaute werden ersetzt (bspw. ä -> a)
- der Quellenhinweis wird größer als der Rest des Textes angezeigt
- das Icon mit dem Pfeil für den Trend ist bei mir nur ein "nackter" Pfeil, ohne Hintergrund und klassische "Emoji"/"Icon"-Optik

**Comment by eknoes** [comment]
Das Problem ist, dass Signal keine Formatierungen unterstützt. Das heißt, wir müssen für fetten / kursiven Text eigentlich [Unicode Mathe Symbole](https://unicode-table.com/de/blocks/mathematical-alphanumeric-symbols/) nutzen. Das passiert hier: https://github.com/eknoes/covid-bot/blob/main/covidbot/signal_interface.py#L76 
Die kursiven Zeichen erscheinen anscheinend größer, wenn sie Mathe Symbole sind.

Wir könnten aber ä durch ae ersetzen und so. Was denkst du dazu?

Zu den Emojis: Wir benutzen sie korrekt, ich weiß leider nicht warum Signal die nicht im Emoji Style rendert. Unser Pfeil ist dieser: https://unicode-table.com/de/2197/

**Comment by eknoes** [comment]
Bei Threema können wir Markdown benutzen
Für Signal hattest du Unicode Umlaute gefunden, oder?

**Comment by errotu** [comment]
[Dieser Konverter](https://yaytext.com/bold-italic/) kann auch Umlaute darstellen. Mir ist nicht ganz klar, welche Unicode-Symbole das genau sind, aber eigentlich müssen wir das für die Integration ja auch nicht wissen, sondern können 𝗕𝘂𝗻𝗱𝗲𝘀𝗹𝗮̈𝗻𝗱𝗲𝗿 und 𝗦𝘁𝗮̈𝗱𝘁𝗲 einfach copy-und-pasten, oder?

**Comment by eknoes** [comment]
Es sind jeweils 2 Zeichen! :O 
https://de.wikipedia.org/wiki/Umlautzeichen

Ich probiere das mal zu integrieren!

**Comment by eknoes** [comment]
Bei Signal immernoch ein Problem, ich glaube die Reihenfolge von dem phonetischen Zeichen und dem Buchstaben muss andersherum, auch wenn es dann mein Editor falsch anzeigt aber Signal korrekt.

**Comment by errotu** [comment]
Wir sollten außerdem mangels Hyperlink-Unterstützung in Threema und Signal das Corona-Dashboard (https://corona.rki.de/) manuell als in Klammern am Ende einfügen.

**Comment by eknoes** [comment]
HTTP Links werden jetzt auch umgewandelt in Text (Link)!
