### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#6]
Welche der Daten, die der Bot verarbeitet (Name, abonnierte Orte, Nachrichten im Chat an den Bot u.ä.), sind für uns einsehbar?

**Comment by eknoes** [comment]
Wir haben prinzipiell Zugriff auf alle Daten eines Telegramprofils das uns eine Nachricht sendet, also Name, Profilbild, etc. Davon benutzen wir bisher nur den Namen und der wird auch nicht gespeichert - das überlege ich zu ändern damit man bei den Inzidenzreports angesprochen wird.

Ansonsten hat jeder Telegramchat eine ID die wir speichern, dazu noch die Verknüpfung dieser ID mit den abonnierten Orten. Nachrichten an den Bot sind nur einsehbar wenn es Kommandos sind, also mit / anfangen. Die werden nur gespeichert wenn das Kommando unbekannt ist.

**Comment by errotu** [comment]
[Datenschutzerklärung](https://github.com/eknoes/covid-bot/wiki/Datenschutz) wurde in das Wiki eingefügt und wird im Readme verlinkt.
