### ISSUE TITLE
Signal Sicherheitsnummer unterschiedlich

### ISSUE THREAD

**Issue by 6e6e58c4** [eknoes/covid-bot#75]
Die Sicherheitsnummer für den Bot-Kontakt passt nicht zur Nummer auf der Webseite

Kontakt in Signal:

> 63924 98065 92222 70496
> 45364 47404 82361 85947
> 91221 29049 44393 75400

Sicherheitsnummer von der Webseite:

> 63924 98065 92222 70496
> 45364 47404 83764 17354
> 85647 36274 54661 31221

Signal: 5.3.12
Android: 10 (rooted)

**Comment by eknoes** [comment]
Danke für deinen Hinweis! Wir haben die Nummer entfernt, die ist je nach Nutzer unterschiedlich. Daher ergibt es keinen Sinn, sie online anzuzeigen!
