### ISSUE TITLE
Telegram-Befehle

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#82]
Ich würde vorschlagen, dass Telegram Befehle auch ohne / versteht. Das würde die Dokumentation/FAQ auch erleichtern, weil sie dann einheitlich für alle Messenger ist.

**Comment by eknoes** [comment]
Wir können es einfach komplett mit / dokumentieren, das geht bei den anderen mittlerweile auch. Gerade bei Telegram werden aber die /commands vervollständigt und angezeigt, was was bedeutet. Außerdem kann man sie direkt antippen!

**Comment by errotu** [comment]
Knapp 50% unser Nutzer:innen verwenden aber kein Telegram. Finde / grundsätzlich nicht besonders benutzerfreundlich. Möchte es bei Telegram ja auch nicht abschaffen (die Vervollständigung hat schon etwas), sondern nur ergänzen, so dass - wie bei den anderen Messengern - der Slash nicht zwingend ist.

**Comment by eknoes** [comment]
Ich habe erwartet, dass es schwerer zu implementieren ist. Das geht jetzt und ist gleich live!
