### ISSUE TITLE
Infos in der Benachrichtigung

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#9]
Der Messenger Newsletter aus Baden-Württemberg beinhaltet neben der Inzidenz noch die folgenden Daten. Können wir die auch (auf Stadt- und/oder Landes- und/oder Bundesebene) darstellen?

> Corona-Bericht für Baden-Württemberg vom 23. Dezember 2020
> 
> Neuinfektionen: 4.391 (gesamt: 221.845)
> Verstorbene: 4.330 (+64)
> Genesene: 157.624 (+3.002)
> Aktuell Infizierte: 59.891 (+1.325)
> 7-Tage-R-Wert: 1,02
> 7-Tage-Inzidenz: 204,5
> Gesamtbelegung der Intensivkapazitäten: 86,0 % (da sind wir ja schon dran)

**Comment by errotu** [comment]
Ich habe mir die Landkreis-Tabelle gerade mal genauer angeschaut. Die folgenden Informationen sollten wir unmittelbar abrufen können:

> **county**
> 7-Tage-Inzidenz: cases7_per_100k_txt
> Neuinfektionen seit gestern: cases
> Neuinfektionen je 100.000 Einwohner:innen seit gestern: cases_per_100k
> Todesfälle seit gestern: deaths

Schwieriger scheint es mit den kumulierten Zahlen zu sein (bspw. Gesamtanzahl der Infektionen oder Todesfälle seit Ausbruch der Pandemie), u.a. auch aktuell Infizierten (also Gesamtanzahl der Infizierten - Gesamtanzahl der Todesfälle - Gesamtanzahl der Genesenen).
Das Feld für Genese scheint derzeit auch nicht gepflegt zu werden ("recovered" ist leer).

**Comment by eknoes** [comment]
Danke! Das baue ich morgen Mal ein!

**Comment by eknoes** [comment]
Das passt nicht, cases scheinen alle Infektionen bisher zu sein, deaths dann auch denke ich :(

**Comment by errotu** [comment]
Stimmt, sorry, da war ich nicht sorgfältig. Aber für uns ist das doch sogar noch besser, oder? Dann müssen wir nur die Daten des Vortages speichern und können kumulierte Angaben mitaufnehmen (ähnlich wie bei der Vorlage aus BW):

> **county**
> 7-Tage-Inzidenz: cases7_per_100k_txt
> Neuinfektionen: cases - cases_yesterday (gesamt: cases)
> Verstorbene: deaths (+[deaths - deaths_yesterday])

**Comment by eknoes** [comment]
Wir haben aktuell noch keine persistenten Covid-Daten, ich habe noch andere RKI Daten bei arcgis gesehen, vielleicht würde ich dann einfach daraus die Zahlen auslesen, dann müssen wir uns da nicht auch um Persistenz kümmern.

**Comment by eknoes** [comment]
Ab morgen (da haben wir dann das erste Mal einen zweiten Datensatz zum vergleichen) gibt es jetzt Neuinfektionen. Wir haben jetzt eine Datenbank und speichern jeden Tag die neuen Daten. Ich glaube, Genesene sind alle die nicht in den letzten 14 Tagen gemeldet worden -> die können wir dann auch ab in 14 Tagen implementieren ;)

**Comment by eknoes** [comment]
Infos sind falsch was Bundesländer angeht und die Summe dementsprechend auch.

**Comment by errotu** [comment]
Ich schließe dieses Issue mal, weil wir inzwischen ja einiges an Daten drin haben, und eröffne separate für die einzelnen Informationen, die noch fehlen. Das sollte es etwas übersichtlicher machen.
