### ISSUE TITLE
no data for NRW?

### ISSUE THREAD

**Issue by MorpheusSohn** [eknoes/covid-bot#90]
Command: abo NRW

" Für NRW stellt das RKI leider keine spezifischen Daten zur Verfügung. Du kannst stattdessen die Zahlen des dazugehörigen Landkreises abrufen

• Dortmund (Kreisfreie Stadt)	5913
• Nordrhein-Westfalen	5

Leider musst du deine Auswahl genauer angeben. Anstatt des kompletten Namens kannst du auch die ID nutzen, also bspw. Abo 5913 für Dortmund (Kreisfreie Stadt)"

**Comment by eknoes** [comment]
Yes, that is already the fix as we do not maintain a list of abbreviations but search online. There, we find "Dortmund" and "NRW" for "NRW", so we show up both as described [here](https://github.com/eknoes/covid-bot/issues/85#issuecomment-777110423). But if you would answer "abo 5" you would subscribe to NRW. 
I see that this is not the optimal solution yet, but I would close this as the fix would be to implement #88 :)
