### ISSUE TITLE
Opt-Out für Diagramme ermöglichen

### ISSUE THREAD

**Issue by errotu** [eknoes/covid-bot#92]
Könnte sinnvoll sein, um Speicherplatz zu sparen.
Anregung kam [auf Reddit](https://www.reddit.com/r/CoronavirusDACH/comments/lh3ld9/wir_haben_einen_covid19_bot_gebaut_der_einmal_am/gmx53ph?utm_source=share&utm_medium=web2x&context=3).

**Comment by eknoes** [comment]
Ah witzig, hab ich gerade auch angelegt: #91 :D

**Comment by errotu** [comment]
Stimmt, mache deshalb den hier auch mal zu!
